#!/bin/bash

BRANCH=$1
TAG=$2
VER=$3

if [ "$BRANCH" == "" ]; then
    echo "Error: branch version is missing"
    echo "help: publish_release.sh  the_branch_version  the_hg_tag the_version_name"
    exit 0
fi

if [ "$TAG" == "" ]; then
    echo "Error: tag name is missing"
    exit 0
fi


if [ "$VER" == "" ]; then
    echo "Error: version is missing"
    exit 0
fi

source $(dirname $0)/../scripts.config.sh

RELEASEDIR=$BUILD_DIR/hgrepo/jelix-$BRANCH
cd $RELEASEDIR

echo "update sources..."

hg pull
hg update $TAG

echo "build packages..."

if [ -d $RELEASEDIR/_dist ]; then
   rm -rf $RELEASEDIR/_dist
fi

/usr/bin/php build/buildjelix.php build/config/jelix-dist-dev.ini
/usr/bin/php build/buildjelix.php build/config/jelix-dist-opt.ini
/usr/bin/php build/buildjelix.php build/config/jelix-dist-gold.ini
/usr/bin/php build/buildapp.php   build/config/testapp-dist.ini
/usr/bin/php build/buildfonts.php build/config/jelix-fonts-dist.ini

cd _dist/

DISTDIR=$DIR_JELIX_SITES/download/www/jelix/releases/$BRANCH/$VER/

if [ ! -d $DISTDIR ]; then
  mkdir $DISTDIR
fi

echo "copy packages on download.j.o..."

cp -a *.gz $DISTDIR
cp -a *.zip $DISTDIR

echo "end."

