#!/bin/bash

BRANCH=$1
TAG=$2
VER=$3

if [ "$BRANCH" == "" ]; then
    echo "Error: branch version is missing"
    echo "help: build_release_doc  the_branch_version  the_hg_tag  the_version_name"
    exit 0
fi

if [ "$TAG" == "" ]; then
    echo "Error: tag name is missing"
    exit 0
fi


if [ "$VER" == "" ]; then
    echo "Error: version is missing"
    exit 0
fi

source $(dirname $0)/../scripts.config.sh

rm -rf $BUILD_DIR/docs/*

RELEASEDIR=$BUILD_DIR/hgrepo/jelix-$BRANCH
cd $RELEASEDIR

hg pull
hg update $TAG

export TESTPATH=$BUILD_DIR/docs/
export DOCSPATH=$DIR_JELIX_SITES/www/reference/$VER
export PHPDOC=$DIR_JELIX_SITES/lib/phpdoc/

make docs

cd $DIR_JELIX_SITES/www/reference/$VER
tar czf $DIR_JELIX_SITES/download/www/jelix/documentation/jelix-"$VER"-apidoc_html.tar.gz *
zip -r $DIR_JELIX_SITES/download/www/jelix/documentation/jelix-"$VER"-apidoc_html.zip *

