{meta_html csstheme 'css/layout.css'}
{meta_html css $j_basepath .'design/2011/design.css'}
{meta_html csstheme 'css/nav.css'}
{meta_html js $j_jelixwww.'jquery/jquery.js'}
<div id="top-box">
	<div class="top-container">
		<div id="accessibility">
			Quick links:
			<a href="#article">Content</a> -
			<a href="#topmenubar">sections</a> -
			<a href="#submenubar">sub sections</a>
		</div>
		{zone 'jcommunity~status'}
		<div id="lang-box">
			<strong>EN</strong>
			<a href="{jurl 'havefnubb~category:view', array('id_cat'=>1, 'ctitle'=>'francais', 'lang'=>'fr_FR')}" hreflang="fr" title="français">FR</a>
		</div>
	</div>
</div>

<div id="header">
    <div class="top-container">

        <h1 id="logo">
             <a href="/" title="Homepage"><img src="/design/logo/logo_jelix_moyen4.png" alt="Jelix" /></a>
        </h1>

        <ul id="topmenubar">
            <li><a href="{jurl 'main~default:indexen'}">About</a></li>
            <li><a href="/articles/en/download">Download</a></li>
            <li class="selected"><a href="/articles/en/documentation">Documentation</a></li>
            <li><a href="/articles/en/community">Community</a></li>
        </ul>
    </div>
</div>
<div id="main-content">
    <div class="top-container">
        <div id="content-header">
            <ul id="submenubar">
				<li class="selected"><a href="{jurl 'havefnubb~default:index'}">Forum</a></li>
				<li><a href="/articles/en/community#mailing-list">Mailing List &amp; IRC</a></li>
				<li><a href="/articles/en/goodies">Goodies</a></li>
            </ul>
        </div>

		<div id="article">
            <!--<div id="article-header">

			</div>-->
			{$MAIN}
			<div id="article-footer">
				{breadcrumb 8, ' > '}
			</div>
		</div>
    </div>
</div>

<div id="footer">
    <div class="top-container">
        <div class="footer-box">
        <p><img src="/design/logo/logo_jelix_moyen5.png" alt="Jelix" /><br/>
            is supported by <a href="http://innophi.com">Innophi</a>.</p>
        <p>Jelix is released under <br/>the LGPL Licence</p>
        </div>

        <div class="footer-box">
            <ul>
                <li><a href="{jurl 'news~default:index', array('lang'=>'en_EN')}">News</a></li>
                <li><a href="/articles/en/faq">FAQ</a></li>
                <li><a href="/articles/en/hall-of-fame">Hall of fame</a></li>
                <li><a href="/articles/en/credits">Credits</a></li>
                <li><a href="/articles/en/support">Contacts</a></li>
                <li><a href="/articles/en/goodies">Goodies</a></li>
            </ul>
        </div>

        <div class="footer-box">
            <ul>
                <li><a href="/articles/en/download/nightly">download nightlies</a></li>
                <li><a href="/articles/en/changelog">changelog</a></li>
                <li><a href="https://github.com/jelix/jelix/issues">issues tracker</a></li>
                <li><a href="https://github.com/jelix/jelix/milestones">roadmap</a></li>
                <li><a href="https://github.com/jelix/jelix/blob/master/CONTRIBUTING.md">How to contribute</a></li>
                <li><a href="https://github.com/jelix/jelix">Code source repository</a></li>
            </ul>
        </div>

        <p id="footer-legend">
            Copyright 2006-2020 Jelix team. <br/>
			{@havefnubb~main.poweredby@} <a href="http://www.havefnubb.org" title="HaveFnuBB!">HaveFnuBB!</a><br/>
            Design by Laurentj. <br/>
            <img src="/design/btn_jelix_powered.png" alt="page generated by a Jelix application" />
        </p>
    </div>
</div>
