#!/bin/bash
set -e
BRANCH=$1
TAG=$2
VER=$3

HELP="help: build_release_doc  the_branch_version  the_git_tag  the_version_name"
HELP2="   ex: build_release_doc 1.4.x  RELEASE_JELIX_1_4_0  1.4.0"

if [ "$BRANCH" == "--help" ]; then
    echo $HELP
    echo $HELP2
    exit 1
fi

if [ "$BRANCH" == "" ]; then
    echo "Error: branch version is missing"
    echo $HELP
    echo $HELP2
    exit 2
fi

if [ "$TAG" == "" ]; then
    echo "Error: tag name is missing"
    echo $HELP
    echo $HELP2
    exit 3
fi

if [ "$VER" == "" ]; then
    echo "Error: version is missing"
    echo $HELP
    echo $HELP2
    exit 4
fi

source $(dirname $0)/scripts.config.sh

rm -rf $BUILD_DIR/docs/*

cd $BUILD_GIT_DIR

git fetch origin
git checkout jelix-$BRANCH
git pull origin jelix-$BRANCH
git checkout refs/tags/$TAG

export TESTPATH=$BUILD_DIR/docs/
export DOCSPATH=$DIR_JELIX_SITES/www/reference/$VER
export PHPDOC=$DIR_JELIX_SITES/lib/phpdoc/

make docs

cd $DIR_JELIX_SITES/www/reference/$VER
tar czf $DIR_JELIX_SITES/download/www/jelix/releases/$BRANCH/$VER/jelix-"$VER"-apidoc_html.tar.gz *
zip -r $DIR_JELIX_SITES/download/www/jelix/releases/$BRANCH/$VER/jelix-"$VER"-apidoc_html.zip *

