#!/bin/bash
set -e
BRANCH=$1
TAG=$2
VER=$3

HELP="help: build_release_doc  the_branch_version  the_git_tag  the_version_name"
HELP2="   ex: build_release_doc 1.4.x  RELEASE_JELIX_1_4_0  1.4.0"

if [ "$BRANCH" == "--help" ]; then
    echo $HELP
    echo $HELP2
    exit 1
fi

if [ "$BRANCH" == "" ]; then
    echo "Error: branch version is missing"
    echo $HELP
    echo $HELP2
    exit 2
fi

if [ "$TAG" == "" ]; then
    echo "Error: tag name is missing"
    echo $HELP
    echo $HELP2
    exit 3
fi

if [ "$VER" == "" ]; then
    echo "Error: version is missing"
    echo $HELP
    echo $HELP2
    exit 4
fi


VER_MAJOR=""
VER_MIDDLE=""

for i in $(echo $VER | tr "." "\n")
do
    if [ "$VER_MAJOR" == "" ]
    then
        VER_MAJOR=$i
    else
        if [ "$VER_MIDDLE" == "" ]
        then
            VER_MIDDLE=$i
        fi
    fi
done

VER_SHORT=$VER_MAJOR"."$VER_MIDDLE

source $(dirname $0)/scripts.config.sh

rm -rf $BUILD_DIR/docs/*

if [ ! -d $BUILD_DIR/phpdoc-cache ]; then
    mkdir $BUILD_DIR/phpdoc-cache
fi

cd $BUILD_GIT_DIR

git fetch origin
git checkout jelix-$BRANCH
git pull origin jelix-$BRANCH
git checkout $TAG

export TESTPATH=$BUILD_DIR/docs/
export DOCSTARGETPATH=$DIR_JELIX_SITES/www/reference/$VER_SHORT
export PHPDOC=$DIR_JELIX_SITES/scripts/vendor/bin/phpdoc
export DOCSCACHEPATH=$BUILD_DIR/phpdoc-cache

make docs

cd $DIR_JELIX_SITES/www/reference/$VER_SHORT
tar czf $DIR_JELIX_SITES/download/www/jelix/releases/$BRANCH/$VER/jelix-"$VER"-apidoc_html.tar.gz *
zip -r $DIR_JELIX_SITES/download/www/jelix/releases/$BRANCH/$VER/jelix-"$VER"-apidoc_html.zip *

