#!/bin/bash

source $(dirname $0)/../scripts.config.sh

rm -rf $BUILD_DIR/docs/*

cd $BUILD_GIT_DIR

git checkout master
git pull origin master

export TESTPATH=$BUILD_DIR/docs/
export DOCSPATH=$DIR_JELIX_SITES/www/reference/trunk
export PHPDOC=$DIR_JELIX_SITES/lib/phpdoc/

make docs

cd $DIR_JELIX_SITES/www/reference/trunk
tar czf $DIR_JELIX_SITES/download/www/jelix/documentation/jelix-trunk-apidoc_html.tar.gz *
zip -r $DIR_JELIX_SITES/download/www/jelix/documentation/jelix-trunk-apidoc_html.zip *

