#!/bin/bash

source $(dirname $0)/../scripts.config.sh

VERSION=$1

if [ "$VERSION" == "" ]; then
    echo "Error: version is missing"
    exit 0
fi

#cd $DIR_JELIX_SITES/portail/scripts/
#echo ""
#echo "build french tutorial draft"
#echo "--------------------"
#echo ""
#php portal.php docbook:index -draft fr:tutoriels:jelixnews tutoriel-jelix-1.0.xml 2>&1 \
# && cd $DIR_JELIX_SITES/portail/var/books \
# && /usr/bin/dblatex -V -p $DIR_JELIX_SITES/install/docbuilder/jelixdoc_params.xsl --texstyle=$DIR_JELIX_SITES/install/docbuilder/jelixdoc_fr.sty tutoriel-jelix-1.0.xml 2>&1 \
# && mv tutoriel-jelix-1.0.pdf $DIR_JELIX_SITES/download/www/jelix/documentation/fr/tutoriel-jelixnews-1.0-draft.pdf \
# && mv tutoriel-jelix-1.0.xml $DIR_JELIX_SITES/download/www/jelix/documentation/fr/tutoriel-jelixnews-1.0-draft.xml


cd $DIR_JELIX_SITES/portail/scripts/
echo ""
echo "build french manual $VERSION draft"
echo "-----------------------------"
echo ""
php portal.php docbook:index -draft fr:manuel-$VERSION manuel-jelix-$VERSION.xml 2>&1 \
 && cd $DIR_JELIX_SITES/portail/var/books \
 && /usr/bin/dblatex -V -p $DIR_JELIX_SITES/install/docbuilder/jelixdoc_params.xsl --texstyle=$DIR_JELIX_SITES/install/docbuilder/jelixdoc_fr.sty manuel-jelix-$VERSION.xml 2>&1 \
 && mv manuel-jelix-$VERSION.pdf $DIR_JELIX_SITES/download/www/jelix/documentation/fr/manuel-jelix-$VERSION-draft.pdf \
 && mv manuel-jelix-$VERSION.xml $DIR_JELIX_SITES/download/www/jelix/documentation/fr/manuel-jelix-$VERSION-draft.xml

cd $DIR_JELIX_SITES/portail/scripts/
echo ""
echo "build french manual 1.3 draft"
echo "-----------------------------"
echo ""
php portal.php docbook:index -draft fr:manuel-1.3 manuel-jelix-1.3.xml 2>&1 \
 && cd $DIR_JELIX_SITES/portail/var/books \
 && /usr/bin/dblatex -V -p $DIR_JELIX_SITES/install/docbuilder/jelixdoc_params.xsl --texstyle=$DIR_JELIX_SITES/install/docbuilder/jelixdoc_fr.sty manuel-jelix-1.3.xml 2>&1 \
 && mv manuel-jelix-1.3.pdf $DIR_JELIX_SITES/download/www/jelix/documentation/fr/manuel-jelix-1.3-draft.pdf \
 && mv manuel-jelix-1.3.xml $DIR_JELIX_SITES/download/www/jelix/documentation/fr/manuel-jelix-1.3-draft.xml
#cd $DIR_JELIX_SITES/portail/scripts/
#echo ""
#echo "build english tutorial draft"
#echo "----------------------------"
#echo ""
#php portal.php docbook:index -draft -lang en_EN en:tutorials:main tutorial-jelix-1.0.xml 2>&1 \
# && cd $DIR_JELIX_SITES/portail/var/books \
# && /usr/bin/dblatex -V -p $DIR_JELIX_SITES/install/docbuilder/jelixdoc_params.xsl --texstyle=$DIR_JELIX_SITES/install/docbuilder/jelixdoc_en.sty tutorial-jelix-1.0.xml 2>&1 \
# && mv tutorial-jelix-1.0.pdf $DIR_JELIX_SITES/download/www/jelix/documentation/en/tutorial-jelixnews-1.0-draft.pdf \
# && mv tutorial-jelix-1.0.xml $DIR_JELIX_SITES/download/www/jelix/documentation/en/tutorial-jelixnews-1.0-draft.xml

cd $DIR_JELIX_SITES/portail/scripts/
echo ""
echo "build english manual $VERSION draft"
echo "------------------------------"
echo ""
php portal.php docbook:index -draft -lang en_EN en:manual-$VERSION manual-jelix-$VERSION.xml 2>&1 \
 && cd $DIR_JELIX_SITES/portail/var/books \
 && /usr/bin/dblatex -V -p $DIR_JELIX_SITES/install/docbuilder/jelixdoc_params.xsl --texstyle=$DIR_JELIX_SITES/install/docbuilder/jelixdoc_en.sty manual-jelix-$VERSION.xml 2>&1 \
 && mv manual-jelix-$VERSION.pdf $DIR_JELIX_SITES/download/www/jelix/documentation/en/manual-jelix-$VERSION-draft.pdf \
 && mv manual-jelix-$VERSION.xml $DIR_JELIX_SITES/download/www/jelix/documentation/en/manual-jelix-$VERSION-draft.xml

cd $DIR_JELIX_SITES/portail/scripts/
echo ""
echo "build english manual 1.3 draft"
echo "------------------------------"
echo ""
php portal.php docbook:index -draft -lang en_EN en:manual-1.3 manual-jelix-1.3.xml 2>&1 \
 && cd $DIR_JELIX_SITES/portail/var/books \
 && /usr/bin/dblatex -V -p $DIR_JELIX_SITES/install/docbuilder/jelixdoc_params.xsl --texstyle=$DIR_JELIX_SITES/install/docbuilder/jelixdoc_en.sty manual-jelix-1.3.xml 2>&1 \
 && mv manual-jelix-1.3.pdf $DIR_JELIX_SITES/download/www/jelix/documentation/en/manual-jelix-1.3-draft.pdf \
 && mv manual-jelix-1.3.xml $DIR_JELIX_SITES/download/www/jelix/documentation/en/manual-jelix-1.3-draft.xml