#!/bin/bash

source $(dirname $0)/../scripts.config.sh

echo "tests on trunk..."
echo "==========================================="

#------ TRUNK

cd $BUILD_GIT_DIR
git checkout master

export TESTPATH=$DIR_TESTS_SITES/trunk
export TESTS_DBPROFILES=$BUILD_DIR/dbprofils.ini.php
export TESTS_CACHEPROFILES=$BUILD_DIR/cache.ini.php
export TESTS_KVPROFILES=$BUILD_DIR/kvprofiles.ini.php

rm -rf $BUILD_DIR/tests/trunk/temp/testapp-cli/*

make tests

echo ""
echo ""


#------- 1.3.x BRANCH

echo "building 1.3.x branch..."
echo "==========================================="

cd $BUILD_GIT_DIR
git checkout jelix-1.3.x

export TESTS_DBPROFILES=$BUILD_DIR/dbprofils12x.ini.php
export TESTPATH=$BUILD_DIR/tests/1.3.x/

rm -rf $BUILD_DIR/tests/1.3.x/temp/testapp-cli/*

make tests

echo ""

