#!/bin/bash

source $(dirname $0)/../scripts.config.sh
FORCE=$1

buildbranch()
{
    echo "building $BRANCH branch..."
    echo "==========================================="
    rm -rf $BUILD_DIR/dist/*

    cd $BUILD_GIT_DIR/jelix
    git checkout $BRANCH
    OLDREV=`cat .git/refs/heads/$BRANCH`
    git pull origin $BRANCH
    NEWREV=`cat .git/refs/heads/$BRANCH`

    if [ "$FORCE" != "" -o "$OLDREV" != "$NEWREV" ]; then
    
    export DISTPATH=$BUILD_DIR/dist/
    export DOWNLOADPATH=$DIR_JELIX_SITES/download/www
    
    make nightlies
    
    mv -f "$DISTPATH"testapp-*.zip    $DOWNLOADPATH/jelix/nightly/
    mv -f "$DISTPATH"testapp-*.tar.gz $DOWNLOADPATH/jelix/nightly/
    
    mv -f "$DISTPATH"jelix-*.zip    $DOWNLOADPATH/jelix/nightly/
    mv -f "$DISTPATH"jelix-*.tar.gz $DOWNLOADPATH/jelix/nightly/


    PACKAGE_NAME_DEV=`cat "$DISTPATH"PACKAGE_NAME_DEV`
    PACKAGE_NAME_OPT=`cat "$DISTPATH"PACKAGE_NAME_OPT`
    PACKAGE_NAME_GOLD=`cat "$DISTPATH"PACKAGE_NAME_GOLD`
    
    cd $DOWNLOADPATH/jelix/nightly
    if  [ -f latest-nightly-$FILENAME-dev.tar.gz ]
    then
        rm latest-nightly-$FILENAME-dev.tar.gz
    fi
    if  [ -f latest-nightly-$FILENAME-opt.tar.gz ]
    then
        rm latest-nightly-$FILENAME-opt.tar.gz
    fi
    if  [ -f latest-nightly-$FILENAME-gold.tar.gz ]
    then
        rm latest-nightly-$FILENAME-gold.tar.gz
    fi

    ln -s "$PACKAGE_NAME_DEV".tar.gz latest-nightly-$FILENAME-dev.tar.gz
    ln -s "$PACKAGE_NAME_OPT".tar.gz latest-nightly-$FILENAME-opt.tar.gz
    ln -s "$PACKAGE_NAME_GOLD".tar.gz latest-nightly-$FILENAME-gold.tar.gz
    
    if  [ -f latest-nightly-$FILENAME-dev.zip ]
    then
        rm latest-nightly-$FILENAME-dev.zip
    fi
    if  [ -f latest-nightly-$FILENAME-opt.zip ]
    then
        rm latest-nightly-$FILENAME-opt.zip
    fi
    if  [ -f latest-nightly-$FILENAME-gold.zip ]
    then
        rm latest-nightly-$FILENAME-gold.zip
    fi
    
    ln -s "$PACKAGE_NAME_DEV".zip latest-nightly-$FILENAME-dev.zip
    ln -s "$PACKAGE_NAME_OPT".zip latest-nightly-$FILENAME-opt.zip
    ln -s "$PACKAGE_NAME_GOLD".zip latest-nightly-$FILENAME-gold.zip
    fi # new rev
    
    echo ""
    echo ""
}

BRANCH="master"
FILENAME="jelix-trunk"
buildbranch
mv -f "$DISTPATH"jbuildtools-nightly.zip $DOWNLOADPATH/jbuildtools/
mv -f "$DISTPATH"jbuildtools-nightly.tar.gz $DOWNLOADPATH/jbuildtools/

mv -f "$DISTPATH"jtpl-*.zip    $DOWNLOADPATH/jtpl/
mv -f "$DISTPATH"jtpl-*.tar.gz $DOWNLOADPATH/jtpl/

BRANCH="jelix-1.4.x"
FILENAME="jelix-1.4.x"
buildbranch
BRANCH="jelix-1.3.x"
FILENAME="jelix-1.3.x"
buildbranch
BRANCH="jelix-1.2.x"
FILENAME="jelix-1.2.x"
buildbranch
